import type { WidgetDefinition } from '../../shared/types/widget'
import { WeatherWidget } from './WeatherWidget'
import { WeatherAlertWidget } from './WeatherAlertWidget'
import { AirQualityWidget } from './AirQualityWidget'
import { SiteSummaryWidget } from './SiteSummaryWidget'
import { BiddingWidget } from './BiddingWidget'
import { ConstructionNewsWidget } from './ConstructionNewsWidget'
import { LawWidget } from './LawWidget'
import { ScheduleWidget } from './ScheduleWidget'
import { TodoWidget } from './TodoWidget'
import { ExchangeRateWidget } from './ExchangeRateWidget'
import { OilPriceWidget } from './OilPriceWidget'
import { MaterialPriceWidget } from './MaterialPriceWidget'
import { MarketSummaryWidget } from './MarketSummaryWidget'
import { AiBriefingWidget } from './AiBriefingWidget'
import { NearbyTrafficWidget } from './NearbyTrafficWidget'

/**
 * Widget Registry (기획 3~4번).
 * 새 Widget을 추가할 때는 컴포넌트를 만들고 이 배열에 메타데이터 1개만 추가하면 된다.
 * Dashboard Grid/WidgetPicker/설정 다이얼로그 등 모든 클라이언트 코드는
 * 이 Registry만 참조하므로 Widget이 하드코딩되지 않는다.
 */
export const WIDGET_REGISTRY: WidgetDefinition[] = [
  {
    id: 'aiBriefing',
    title: 'AI 브리핑',
    description: '오늘 확인해야 할 안전/일정/입찰/시장 정보를 AI가 요약합니다',
    category: '업무',
    icon: 'Sparkles',
    component: AiBriefingWidget,
    defaultSize: { w: 2, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    refreshInterval: 0,
    supportsLocation: false,
    supportsManualRefresh: true,
  },
  {
    id: 'calendar',
    title: '일정관리',
    description: '이번 주 예정된 회의/점검/자재반입 등 일정을 확인합니다',
    category: '업무',
    icon: 'Calendar',
    component: ScheduleWidget,
    defaultSize: { w: 1, h: 2 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 3 },
    refreshInterval: 5 * 60 * 1000,
    supportsLocation: false,
    supportsManualRefresh: true,
    detailPath: '/schedule',
  },
  {
    id: 'todo',
    title: '할일관리',
    description: '진행 중인 할 일을 우선순위 순으로 확인하고 완료 처리합니다',
    category: '업무',
    icon: 'CheckSquare',
    component: TodoWidget,
    defaultSize: { w: 1, h: 2 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 3 },
    refreshInterval: 5 * 60 * 1000,
    supportsLocation: false,
    supportsManualRefresh: true,
    detailPath: '/todo',
  },
  {
    id: 'weather',
    title: '건설날씨',
    description: '현장 위치의 기상 정보와 작업 유형별 위험도를 확인합니다',
    category: '현장환경',
    icon: 'CloudSun',
    component: WeatherWidget,
    defaultSize: { w: 1, h: 2 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 2 },
    refreshInterval: 15 * 60 * 1000,
    supportsLocation: true,
    supportsManualRefresh: true,
  },
  {
    id: 'weatherAlert',
    title: '기상·재난특보',
    description: '현장 인근 지역에 발효 중인 기상/재난 특보를 확인합니다',
    category: '현장환경',
    icon: 'AlertOctagon',
    component: WeatherAlertWidget,
    defaultSize: { w: 1, h: 1 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 2 },
    refreshInterval: 7 * 60 * 1000,
    supportsLocation: true,
    supportsManualRefresh: true,
  },
  {
    id: 'airQuality',
    title: '대기질',
    description: '현장 인근 미세먼지·초미세먼지·오존 등급을 확인합니다',
    category: '현장환경',
    icon: 'Wind',
    component: AirQualityWidget,
    defaultSize: { w: 1, h: 1 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 2 },
    refreshInterval: 30 * 60 * 1000,
    supportsLocation: true,
    supportsManualRefresh: true,
  },
  {
    id: 'nearbyTraffic',
    title: '인근 교통정보',
    description: '현장 인근 주요도로의 속도와 사고·공사·통제 정보를 확인합니다',
    category: '현장환경',
    icon: 'CarFront',
    component: NearbyTrafficWidget,
    defaultSize: { w: 1, h: 2 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 3 },
    refreshInterval: 5 * 60 * 1000,
    supportsLocation: true,
    supportsManualRefresh: true,
  },
  {
    id: 'siteSummary',
    title: '오늘의 현장',
    description: '투입 인원, 작업 종류, 장비, 위험 작업 현황을 요약합니다',
    category: '현장환경',
    icon: 'HardHat',
    component: SiteSummaryWidget,
    defaultSize: { w: 1, h: 2 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 2 },
    refreshInterval: 10 * 60 * 1000,
    supportsLocation: true,
    supportsManualRefresh: true,
  },
  {
    id: 'bidding',
    title: '관심입찰',
    description: '관심 등록한 공공/민간 입찰 공고와 마감일을 확인합니다',
    category: '수주정보',
    icon: 'Gavel',
    component: BiddingWidget,
    defaultSize: { w: 1, h: 2 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 3 },
    refreshInterval: 45 * 60 * 1000,
    supportsLocation: false,
    supportsManualRefresh: true,
    detailPath: '/bids',
  },
  {
    id: 'constructionNews',
    title: '건설뉴스',
    description: '건설업 관련 최신 뉴스를 확인합니다',
    category: '수주정보',
    icon: 'Newspaper',
    component: ConstructionNewsWidget,
    defaultSize: { w: 1, h: 2 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 3 },
    refreshInterval: 20 * 60 * 1000,
    supportsLocation: false,
    supportsManualRefresh: true,
  },
  {
    id: 'law',
    title: '법령·제도',
    description: '건설 관련 법령·제도의 최신 개정 현황을 확인합니다',
    category: '수주정보',
    icon: 'Scale',
    component: LawWidget,
    defaultSize: { w: 1, h: 1 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 2 },
    refreshInterval: 12 * 60 * 60 * 1000,
    supportsLocation: false,
    supportsManualRefresh: true,
  },
  {
    id: 'exchangeRate',
    title: '환율',
    description: 'USD/EUR/JPY/CNY 등 주요 환율 시세를 확인합니다',
    category: '경제원가',
    icon: 'DollarSign',
    component: ExchangeRateWidget,
    defaultSize: { w: 1, h: 1 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 2 },
    refreshInterval: 45 * 60 * 1000,
    supportsLocation: false,
    supportsManualRefresh: true,
  },
  {
    id: 'oilPrice',
    title: '유가',
    description: '국내외 유가(경유/휘발유/두바이유 등) 시세를 확인합니다',
    category: '경제원가',
    icon: 'Fuel',
    component: OilPriceWidget,
    defaultSize: { w: 1, h: 1 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 2 },
    refreshInterval: 45 * 60 * 1000,
    supportsLocation: false,
    supportsManualRefresh: true,
  },
  {
    id: 'materialPrice',
    title: '주요자재가격',
    description: '철근/시멘트/H형강 등 주요 자재가격을 확인합니다 (Mock 데이터)',
    category: '경제원가',
    icon: 'Package',
    component: MaterialPriceWidget,
    defaultSize: { w: 1, h: 2 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 3 },
    refreshInterval: 6 * 60 * 60 * 1000,
    supportsLocation: false,
    supportsManualRefresh: true,
  },
  {
    id: 'marketSummary',
    title: '건설시장 종합',
    description: '환율·유가·자재가격 핵심 지표를 한 눈에 확인합니다',
    category: '경제원가',
    icon: 'LineChart',
    component: MarketSummaryWidget,
    defaultSize: { w: 1, h: 1 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 2, h: 2 },
    refreshInterval: 45 * 60 * 1000,
    supportsLocation: false,
    supportsManualRefresh: true,
  },
]

export function getWidgetDefinition(id: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.find((w) => w.id === id)
}

export const WIDGET_CATEGORIES = ['업무', '현장환경', '수주정보', '경제원가'] as const
